### PR TITLE
wifi stability improved

### PR DESCRIPTION
**Pull request by nicelight**
Hi. Thank you very much for your great work. I will use this project with my Homeassistant server for home automatisation. 
I added some code to improve wifi, here is updates:
- each 10 seconds esp32-cam checks wifi stability and restarts if connection can't be restored. 
- possibility to give static wifi IP address to esp32-cam.

best regards!

### CODE REVIEW

**Comment by arkhipenko** [comment]
I am not maintaining the Arduino IDE versions:
The latest, more robust code is here: 
https://github.com/arkhipenko/esp32-mjpeg-multiclient-espcam-drivers/tree/master/PlatformIO

**Comment by nicelight** [comment]
Hi. I also make code mostly in PIO 
But my disciples unfortunatelly cant make their workspace properly to feel free in PIO so I am trying to do easy way for most people who not really common with electronics but want to use it in easy way. 
Any way, thanks at least for answer. Have a nice day)

**Comment by arkhipenko** [comment]
Sorry for the short answer. Really appreciate you taking the time.
The repo I mentioned uses WiFi manager, and has the WiFi autoreconnect feature on - so it is taken care of by the firmware. 
WiFi manager also allows custom fields, so static IP could be implemented into it - that would be a good PR. :)

**Comment by nicelight** [comment]
Thanx for idea. I will check it)

**Comment by nicelight** [comment]
I spend half day to add to this project web OTA ( as for example ElegantOTA) but it doesnt works fine. With simple web server just get error and rebooting in process of uploading firmware, and Asyncweb server  doesnt starts with project) 
What about you, didn't you implement web OTA to this project on PlatformIO?

**Pull request closed without merging**
